#!/usr/bin/with-contenv bash

while true; do
  DATA=$(tailscale status --json)

  echo "$DATA" | jq -c '.Peer' | \
  mosquitto_pub \
    -h "$MQTT_HOST" \
    -u "$MQTT_USER" \
    -P "$MQTT_PASS" \
    -t "tailscale/peers/raw" \
    -r \
    -l

  sleep 60
done
