---
build_from:
  aarch64: ghcr.io/hassio-addons/base:17.2.2
  amd64: ghcr.io/hassio-addons/base:17.2.2
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: SmartThings MQTT Bridge"
  org.opencontainers.image.description: "Bridge Samsung SmartThings devices to MQTT."
  org.opencontainers.image.source: "https://github.com/gdam12886/ha-addons-repository"
  org.opencontainers.image.licenses: "MIT"
